# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016' # https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

#- task: VSTest@2
#  inputs:
#    testSelector: 'testAssemblies'
#    testAssemblyVer2: |
#      **\*test*.dll
#      !**\*TestAdapter.dll
#      !**\obj\**
#    searchFolder: '$(System.DefaultWorkingDirectory)'
#    package: $(System.ArtifactsDirectory)/**/*.zip    
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

# https://docs.microsoft.com/da-dk/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'    
    publishLocation: 'FilePath'
    TargetPath: '$(System.DefaultWorkingDirectory)'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Microsoft Imagine(edaa3574-d80b-4170-9ad2-f9b619fb3f91)'
#     appType: 'webApp'
#     appName: 'anbo-simpleRest'
#     #package: 'D:\a\1\s\simpleRESTservice\bin\Release\netcoreapp2.1\simpleRESTservice.dll'
#     package: 'D:\a\1\a\simpleRESTservice.dll'
#     #deploymentMethod: 'auto'
#     deploymentMethod: runFromPackage
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Imagine(edaa3574-d80b-4170-9ad2-f9b619fb3f91)'
    appType: 'webApp'
    WebAppName: 'anbo-simpleRest'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


